name: co-labora
description: Oficina colaborativa (coworking) en Managua, Nicaragua
url: http://co-labora.net

safe:        false
auto:        false
server:      false
server_port: 4000
url: http://localhost:4000
